"""
Change description type of twitter user

Revision ID: 02747b0756ae
Revises: 4775a7d531e0
Create Date: 2017-12-02 19:55:33.628278
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02747b0756ae'
down_revision = '4775a7d531e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_user', 'description', existing_type=sa.String(length=160), type_=sa.Text)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_user', 'description', existing_type=sa.Text, type_=sa.String(length=160))
    # ### end Alembic commands ###
