"""
Add match related columns and remove unneccesary columns

Revision ID: 1f72e7b6c260
Revises: 2dd2abc4b8a9
Create Date: 2018-04-21 21:21:40.819943
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f72e7b6c260'
down_revision = '2dd2abc4b8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user', sa.Column('match_name', sa.String(length=50), nullable=True))
    op.add_column('twitter_user', sa.Column('match_ratio', sa.Integer()))
    op.drop_column('twitter_user', 'statuses_count')
    op.drop_column('twitter_user', 'followers_count')
    op.drop_column('twitter_user', 'friends_count')
    op.drop_column('twitter_user', 'description')
    op.drop_column('twitter_user', 'favourites_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user', sa.Column('favourites_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('twitter_user', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('twitter_user', sa.Column('friends_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('twitter_user', sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('twitter_user', sa.Column('statuses_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('twitter_user', 'match_ratio')
    op.drop_column('twitter_user', 'match_name')
    # ### end Alembic commands ###
