"""
Add connection change

Revision ID: 2dd2abc4b8a9
Revises: 02747b0756ae
Create Date: 2018-04-01 21:44:01.581062
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd2abc4b8a9'
down_revision = '02747b0756ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_connection_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_added', sa.Boolean(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['twitter_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_connection_change')
    # ### end Alembic commands ###
