"""
Add twitter entry table

Revision ID: 46e5ac59a247
Revises: 93c9cad4eadf
Create Date: 2017-11-30 18:07:07.645114
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e5ac59a247'
down_revision = '93c9cad4eadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['twitter_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_entry')
    # ### end Alembic commands ###
