"""
Add twitter user, connection and entry

Revision ID: 4775a7d531e0
Revises: 
Create Date: 2017-12-02 19:13:53.926043
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4775a7d531e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('screen_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('friends_count', sa.Integer(), nullable=False),
    sa.Column('favourites_count', sa.Integer(), nullable=False),
    sa.Column('statuses_count', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['twitter_user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['twitter_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['twitter_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_entry')
    op.drop_table('twitter_connection')
    op.drop_table('twitter_user')
    # ### end Alembic commands ###
