"""
Readd friend and follower counts

Revision ID: e2d140e07d12
Revises: 115ac8a54c99
Create Date: 2018-05-01 13:41:47.105415
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d140e07d12'
down_revision = '115ac8a54c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_user', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('twitter_user', sa.Column('friends_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_user', 'friends_count')
    op.drop_column('twitter_user', 'followers_count')
    # ### end Alembic commands ###
